### ISSUE TITLE
Postgres Storage

### ISSUE THREAD

**Issue by timonv** [bosun-ai/swiftide#158]
Postgres with PGVector is popular for good reasons and it makes sense to support it. There are two parts to the integration, implementing `Persist` and implementing (various) search strategies.

Before implementation; since Postgres is not schemaless, I'm especially interested in a setup that alligns with other forms of storage and how we deal with additional fields (ie metadata).

**Comment by shamb0** [comment]
Hello @timonv , I am interested to work on this, Could you please assign it to me.

**Comment by timonv** [comment]
Hi @shamb0, thanks for your interest, ofcourse! I'd suggest to split up the PRs in (at least) two, indexing and querying seperately. What are your thoughts on schema management?

**Comment by shamb0** [comment]
Thanks @timonv, Sounds Good. I will make two PR's. :-)
