### ISSUE TITLE
Single definition of batch size in indexing vs transformers

### ISSUE THREAD

**Issue by timonv** [bosun-ai/swiftide#233]
Batch size in indexing should either be on the pipeline only and inherited by the transformer, or set on the transformer only and used by the pipeline.

EmbeddingModels currently have a double batch size, it's confusing and not needed. I think the latter with a sane default could have the cleanest api.

**Comment by mdabir1203** [comment]
Can you please clarify a bit more where to look for the code so I can help fix the issue

**Comment by timonv** [comment]
@mdabir1203 Thanks for the interest and wanting to pick this up! 🚀 

Currently there are two batch sizes defined, one in the indexing pipeline itself. The indexing pipeline needs to know how many chunks it should batch up, and will send those as a list to the batch transformer. However, some batch transformers also have a batch size (regardless of the pipeline's). FastEmbed for instance takes a batch size for embeddings for internally in its models as well.

This leads to the following weird api:

```rust
let batch_size = 100;

       Pipeline::from_loader(loaders::FileLoader::new(tempdir.path()).with_extensions(&["rs"]))
            .then_in_batch(batch_size, transformers::Embed::new(FastEmbed::builder().batch_size(batch_size).build().unwrap()))
 
```

It's double and it needs to be aligned. Specifically for FastEmbed, the default is None, so then the library will use it's own default batch size.

Ideally I'd have the batch size specified once for transformers, and only on the transformer, with sensible defaults (256 is great). This would need to be set in pipeline defaults. Transformers with children that determine the batch size would need to propagate it.

See the Persist trait for how I think it should work.

Then in batch would be like this instead:
```rust
.then_in_batch(transformers::Embed::new(FastEmbed::builder().batch_size(batch_size).build().unwrap()
```

For example, a possible implementation could look like this:
* Remove batch size as argument from then_in_batch
* Add a batch_size -> Option<usize> to the BatchTransformerTrait
* I think Embed and SparseEmbed might need a batch size then given the generics, maybe there's a nice way to avoid it.
* Ensure any integrations with batch sizes have sensible defaults if needed, otherwise they could use the default from the pipeline, afaik mostly fastembed.
* Add a default_batch_size to PipelineDefaults
* In then_in_batch, it should try to get the batch size from the transformer or fall back to the pipeline default.

**Comment by mdabir1203** [comment]
Can you show which file and which line of the code is this. I have a probable implementation in my mind like this. But I need to see a bit more : 

```
// Define a struct for pipeline defaults
struct PipelineDefaults {
    default_batch_size: usize,
}

// Define the BatchTransformerTrait
trait BatchTransformerTrait {
    fn batch_size(&self) -> Option<usize>;
}

// Example implementation for Embed
struct Embed {
    batch_size: Option<usize>,
}

impl BatchTransformerTrait for Embed {
    fn batch_size(&self) -> Option<usize> {
        self.batch_size
    }
}

// Modify the Pipeline struct
struct Pipeline {
    defaults: PipelineDefaults,
}

impl Pipeline {
    fn then_in_batch(self, transformer: impl BatchTransformerTrait) {
        let batch_size = transformer.batch_size().unwrap_or(self.defaults.default_batch_size);
        // Proceed with processing using the determined batch_size
    }
}

// Usage
fn main() {
    let defaults = PipelineDefaults { default_batch_size: 100 };
    let pipeline = Pipeline { defaults };

    let embed_transformer = Embed { batch_size: None }; // No specific batch size set

    pipeline.then_in_batch(embed_transformer); // Uses default batch size of 100
}
```

**Comment by timonv** [comment]
@mdabir1203 Almost everything is in swiftide-indexing, traits and core share types are in swiftide-core. 

```rust

// Usage
fn main() {
    let defaults = PipelineDefaults { default_batch_size: 100 };
    let pipeline = Pipeline { defaults };

    let embed_transformer = Embed { batch_size: None }; // No specific batch size set

    pipeline.then_in_batch(embed_transformer); // Uses default batch size of 100
}
```

What's this? Have you looked at our examples or tried to run a pipeline? For searching code ripgrep and rust-analyzer are your friends. Best of luck!
