### ISSUE TITLE
windows not run

### ISSUE THREAD

**Issue by cyberdoors** [bosun-ai/swiftide#299]
swiftide-core-0.11.1\src\node.rs:24:9
````
  os::unix::ffi::OsStrExt,
   |         ^^^^ could not find `unix` in `os`
````

**Comment by timonv** [comment]
Hi @cyberdoors, thanks for reporting the issue. Officially we don't support Windows, as some integrations simply don't run on the platform. Do you have a full stacktrace for me? Then I can take a look.

**Comment by timonv** [comment]
Closing this. Feel free to re-open the issue with more information, I'm happy to help.
