### ISSUE TITLE
Add forum/"GitHub discussions"

### ISSUE THREAD

**Issue by InAnYan** [bosun-ai/swiftide#429]
I have questions for you library, but I can't any suitable place except GitHub issues or Discord.

IMHO, maybe it's better to use GitHub discussions or some forum for asking questions, as they are more suited for this? And Discord is made for other purposes

**Comment by timonv** [comment]
@InAnYan Great asuggestion, I hadn't considered. I'll set it up right away 🙏

**Comment by timonv** [comment]
It's enabled!
