### ISSUE TITLE
Named / multiple vector support for Qdrant

### ISSUE THREAD

**Issue by timonv** [bosun-ai/swiftide#62]
The current Qdrant implementation by default only supports a single vector. By supporting named vectors we enable two highly desired features:

* **Different metadata embedding modes** Currently we add the metadata to the chunk and then embed. Ideally we can also choose not to, or do both, and create and add vectors for each field. This might be a requirement for this issue.
* **Sparse vector support** Sparse vectors are great for lightweight hybrid search looking for more exact matches. 

See https://qdrant.tech/documentation/concepts/collections/#collection-with-multiple-vectors.

**Comment by pwalski** [comment]
Would such implementation be ok:

1. Introduce public `transformers::embed::EmbedMode { WithMetadata, WithoutMetadata, Both }` type.
2. Update `transformers::embed::Embed` by creating a Builder (optionally replacing `with_concurrency` with `concurrency` derive_builder generated setter), and adding `embed_mode` field/builder setter with a default value `WithMetadata`.
3. Update `ingestion::IngestionNode` to have `vectors: Option<HashMap<String,<Vec<f32>>>>` instead of a `vector` field (it will do for now, but might require some `VectorType` to support Sparse vectors)
4. Make `impl BatchableTransformer for Embed::batch_transform` to create embeddable chunks depending on selected `EmbedMode` and add embeddings vectors to the map.
5. Make `impl Qdrant::create_index_if_not_exists` to create `qdrant_client::qdrant::CreateCollection` struct with `vectors_config` field of `Config::ParamsMap` value containing named vectors. Its value would depend on selected `EmbedMode`. There could be a default vec named _"WithMetadata"_, or _"WithoutMetadata"_, or both vectors. Their length would come from `Qdrant::vector_size` (but it could as well come from `impl EmbeddingModel` - if I understand correctly the length of dense vecs depends on selected embed model).
6. Tests/examples/etc.

?

Will it be enough to configure named vectors using only an `EmbedMode` field in `Embed` struct, or will users need to configure e.g. a different `Distance` for each vector, so introduction of some `vector_config` field in `Qdrant` builder will be necessary?
It could not even give user control over vector names, but instead it could have some dedicated config types for each `EmbedMode`.


Disclaimer: after a short break from Rust I need to do some tasks as an reminder. I am unfamiliar with RAG pipelines, so I do not know e.g. how much control over vectors users may need.

**Comment by timonv** [comment]
Hi Pwalski, thanks for being interested and offering your help! Sounds really good. 

Design wise I'd like to make sure we do the following things:
* Sane and minimal config defaults, get started without a builder, then use a builder when more configuration is required. If even more is needed, build the client and users can add it to the wrapper.
* See if we can get to a point where there is minimal duplication of configuration; for embedding for instance, the transformer needs to know what to embed and how and storage needs to know what to store and the dimensions; it's interesting to think about which part is responsible for what.
* Modularity should be maintained such that when adding more databases and other embedding models, the storage can decide how it should persist the Node.

> Introduce public transformers::embed::EmbedMode { WithMetadata, WithoutMetadata, Both } type.

👍 Perhaps naming wise we can get it more inline with what happens, something like SingleBlob, NamedFields, Both. Feels like a mouthful though, perhaps you have a better idea.

> Update transformers::embed::Embed by creating a Builder (optionally replacing with_concurrency with concurrency derive_builder generated setter), and adding embed_mode field/builder setter with a default value WithMetadata.

That's an interesting view. Initially I was thinking of having the EmbedMode as a property on the IngestionNode, perhaps inheriting it from the pipeline as a global default. So then the IngestionNode owns its data, it's up to an Embedder to embed depending on the mode, and it's up to the storage to persist depending on the mode and any other config it needs. I'm very open to alternative solutions.

> Make ingestion::IngestionNode to have vectors: Option<HashMap<String,<Vec<f32>>>> instead of a vector field (it will do for now, but might require changes to support Sparse vectors)

👍 I think it will work fine with sparse, as long as the dimensions can differ. How will this work if there is a single embedding? There is also a type alias for Embeddings.

> Make impl BatchableTransformer for Embed::batch_transform to create an embeddable chunks depending on selected EmbedMode and add embeddings vectors to the map.

👍 Sounds good. If it's complicated to have one do both, creating a new transformer is also an option.

> Make impl Qdrant::create_index_if_not_exists to create qdrant_client::qdrant::CreateCollection struct with vectors_config field of Config::ParamsMap value containing named vectors. Its value would depend on selected EmbedMode. There could be a default vector named "WithMetadata", or "WithoutMetadata", or both vectors. Their length would come from Qdrant::vector_size (but it could as well come from impl EmbeddingModel - if I understand correctly the length of dense vecs depends on selected embed model).

This is food for thought, I can imagine multiple use cases:
* Querying on the aggregated metadata instead of the full document
* Querying on a single metadata field
* Querying on a sparse vector of a metadata field
* Querying on a sparse vector that's on it's own
Which to me also raises the question if everything should be stored as is, or if we want (in the future) some way to define that genericly. Maybe it's possible to derive (part of) the schema of a node in the schema, with the option to override, i.e. wait until the first node comes through, then create a derived schema lazily. Just brainfarting here, probably all future material.

For now though, I think:
I'd prefer it if the default is a single vector (EmbedMode::WithMetadata). On EmbedMode::Without it will create named vectors for each metadata field and the text itself. For Both it does both with the metadata also embedded. Then for Qdrant, in the builder we can allow full customization, and we can provide some default or helper to make the setup a bit easier (Qdrant rust api is imo pretty rough). I.e. having a '.vector_names(vector_names: &[&str])` on the builder that takes the already given dimensions with a default distance. If users then want to fully configure it, they can provider their own implementation.

> Disclaimer: after a short break from Rust I need to do some tasks as an exercise. I am unfamiliar with RAG pipelines, so I do not know e.g. how much control over vectors users may need.

Hell yeah! Sounds like you already got it under control!

Thanks again for offering your support <3. Named vectors are very high on the priority list as it will open up a lot of ways to improve search. Let me know if there is anything I can help with.

**Comment by timonv** [comment]
Would just like to add that the embedding transformer currently assumes that the ordering of vectors is the same as the requested text. For OpenAI I haven't seen it differently, but that might actually be a potential problem when testing if this works. There's some performance considerations here as well.

**Comment by pwalski** [comment]
> Initially I was thinking of having the EmbedMode as a property on the IngestionNode, perhaps inheriting it from the pipeline as a global default. So then the IngestionNode owns its data, it's up to an Embedder to embed depending on the mode, and it's up to the storage to persist depending on the mode and any other config it needs.

Makes sense.

> I'd prefer it if the default is a single vector (EmbedMode::WithMetadata). On EmbedMode::Without it will create named vectors for each metadata field and the text itself. For Both it does both with the metadata also embedded.

The only problem I see is that it could be confusing having a vector `WithMetadata` sometimes as a default unnamed vector, and sometimes as a one of named vectors. Having said that I have no idea if it would be weird to store a single named vector in Qdrant, so I am fine with proposed approach.

> For now though, I think:
I'd prefer it if the default is a single vector (EmbedMode::WithMetadata). On EmbedMode::Without it will create named vectors for each metadata field and the text itself. For Both it does both with the metadata also embedded. Then for Qdrant, in the builder we can allow full customization, and we can provide some default or helper to make the setup a bit easier (Qdrant rust api is imo pretty rough). I.e. having a '.vector_names(vector_names: &[&str])` on the builder that takes the already given dimensions with a default distance. If users then want to fully configure it, they can provider their own implementation.

Will do that. You can assign me to the issue.

**Comment by timonv** [comment]
> The only problem I see is that it could be confusing having a vector WithMetadata sometimes as a default unnamed vector, and sometimes as a one of named vectors. Having said that I have no idea if it would be weird to store a single named vector in Qdrant, so I am fine with proposed approach.

Agree, it does sound weird, maybe a better name pops up when working on it. What I dislike about the with/without metadata is that it doesn't really communicate what it does, maybe something like:
```rust
enum EmbedMode {
  SingleWithMetadata, 
  PerField, 
  Both
}
```

Naming always is the hardest part 👶 

I was thinking about the config api a bit. Looking at the docs, the python / TS api is actually really concise. Beats me why the Rust api isn't (audience and priorities I bet). I see no reason why the Rust api cannot be just as concise. https://qdrant.tech/documentation/concepts/collections/

> Will do that. You can assign me to the issue.

<3 Let me know if there is anything I can help with

**Comment by timonv** [comment]
@pwalski heads up, the qdrant client had a significant update, I'll update it in swiftide asap

**Comment by pwalski** [comment]
I noticed `qdrant_client::client::QdrantClient` is deprecated in favor of `qdrant_client::Qdrant`.
You can update version only, and I could migrate to new client.
BTW I have some problem with deciding how to configure default vectors.
Initially I wanted to change
`Persist::setup(&self) -> Result<()>` into `Persist::setup(&self, embed_mode: EmbedMode) -> Result<()>` so the pipeline could pass `EmbedMode` it was started with which would let Qdrant integration to configure default vectors. The problem is only `Qdrant` would use this param.

**Comment by timonv** [comment]
> I noticed `qdrant_client::client::QdrantClient` is deprecated in favor of `qdrant_client::Qdrant`. You can update version only, and I could migrate to new client.
I'll update it properly asap :-)

> BTW I have some problem with deciding how to configure default vectors. Initially I wanted to change `Persist::setup(&self) -> Result<()>` into `Persist::setup(&self, embed_mode: EmbedMode) -> Result<()>` so the pipeline could pass `EmbedMode` it was started with which would let Qdrant integration to configure default vectors. The problem is only `Qdrant` would use this param. EDIT: Nvm, Passing `EmbedMode` in `Persist::setup` would require storing it somewhere in `IngestionPipeline`, while method `with_embed_mode` I added only adds mapping to ingestion stream which sets `node.embed_mode`. Instead for now I will force user to configure `EmbedMode` both in pipeline, and `Qdrant` client.

I think that you might not need it at all in the storage. IngestionNodes will have a hashmap in vectors with <name, vector>. Maybe it can try to map that to the collection it got configured with and error if it does not match?
